name: gitmine
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  get_it: ^7.2.0
  process_run: ^0.12.3+2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
